EntityCombat:
  enabled: false
  maxDistance: 5
EntityReach:
  enabled: true
  maxDistance: 4.25
BlinkMovement:
  enabled: false
  maxDistance: 10
Reach:
  enabled: true
  maxDistance: 5 # Recommended value: 5
BlockInteractions:
  enabled: false
  LoSBuffer: 1.5 # Recommended value:
  LoSBufferTime: 250 # Recommended value: BROKEN
InventoryMovement: # Inventory Movement is not considered cheating anymore
  enabled: false

actions:
  InventoryMovement:
    #- "sendWebhook:Potential cheating: Inventory movement"
    #- "log:USER %player% CHEATED WITH INVENTORY MOVEMENT"
    #- "cancelEvent"
  noLoS:
    #- "sendWebhook:Potential cheating: No line of sight"
    #- "cancelEvent"
    #- "log:USER %player% CHEATED WITH NO LoS"
  Reach:
    - "sendWebhook:Player %player% has triggered Reach event"
    #- "cancelEvent"
    #- "log:USER %player% CHEATED WITH REACH"
  EntityCombat:
    #- "sendWebhook:Potential cheating: Entity combat"
    #- "cancelEvent"
    #- "log:USER %player% CHEATED WITH ENTITY COMBAT"
  BlinkMovement:
    #- "sendWebhook:Potential cheating: Movement"
    #- "cancelEvent"
    #- "log:USER %player% CHEATED WITH BLINK MOVEMENT"
  EntityReach:
    - "sendWebhook:Player %player% has triggered EntityReach event"
    #- "cancelEvent"
    #- "log:USER %player% CHEATED WITH ENTITY REACH"

settings:
  SendMessage:
    toOPs: false
    toOffender: false
  Debug:
    enabled: true
    SendWebhook: false
    toConsole: true
  Webhook: ""