name: Barium
version: '${version}'
main: org.its3rr0rswrld.barium.Barium
api-version: '1.20'

resources:
  - config.yml

commands:
    bDebug:
        description: Debug command
        permission: barium.debug
        aliases:
            - bd
        permission-message: '&cYou do not have permission to use this command.'